// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzIEd3J1j9gQCMhrvJ00v72IEtRFW_Ebw',
    appId: '1:447063837607:web:b7c7e852472a080bb2c482',
    messagingSenderId: '447063837607',
    projectId: 'fir-demo-app-47a84',
    authDomain: 'fir-demo-app-47a84.firebaseapp.com',
    storageBucket: 'fir-demo-app-47a84.firebasestorage.app',
    measurementId: 'G-6VVKH0YXYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP1u1BAa8qC04LM8ZRAvKd4Q-n9KrofO0',
    appId: '1:447063837607:android:3bb56159dab8439ab2c482',
    messagingSenderId: '447063837607',
    projectId: 'fir-demo-app-47a84',
    storageBucket: 'fir-demo-app-47a84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACeHxzpS3EvfgAAaYhmra0NAF1AQoGKUA',
    appId: '1:447063837607:ios:40a5c213e24399e2b2c482',
    messagingSenderId: '447063837607',
    projectId: 'fir-demo-app-47a84',
    storageBucket: 'fir-demo-app-47a84.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutter',
  );
}
